export const ACCOUNT_FETCH_REQUEST = 'ACCOUNT_FETCH_REQUEST'
export const ACCOUNT_FETCH_SUCCESS = 'ACCOUNT_FETCH_SUCCESS'
export const ACCOUNT_FETCH_FAIL = 'ACCOUNT_FETCH_FAIL'

export const ACCOUNT_LOOKUP_REQUEST = 'ACCOUNT_LOOKUP_REQUEST'
export const ACCOUNT_LOOKUP_SUCCESS = 'ACCOUNT_LOOKUP_SUCCESS'
export const ACCOUNT_LOOKUP_FAIL = 'ACCOUNT_LOOKUP_FAIL'

export const ACCOUNT_FOLLOW_REQUEST = 'ACCOUNT_FOLLOW_REQUEST'
export const ACCOUNT_FOLLOW_SUCCESS = 'ACCOUNT_FOLLOW_SUCCESS'
export const ACCOUNT_FOLLOW_FAIL = 'ACCOUNT_FOLLOW_FAIL'

export const ACCOUNT_UNFOLLOW_REQUEST = 'ACCOUNT_UNFOLLOW_REQUEST'
export const ACCOUNT_UNFOLLOW_SUCCESS = 'ACCOUNT_UNFOLLOW_SUCCESS'
export const ACCOUNT_UNFOLLOW_FAIL = 'ACCOUNT_UNFOLLOW_FAIL'

export const ACCOUNT_BLOCK_REQUEST = 'ACCOUNT_BLOCK_REQUEST'
export const ACCOUNT_BLOCK_SUCCESS = 'ACCOUNT_BLOCK_SUCCESS'
export const ACCOUNT_BLOCK_FAIL = 'ACCOUNT_BLOCK_FAIL'

export const ACCOUNT_UNBLOCK_REQUEST = 'ACCOUNT_UNBLOCK_REQUEST'
export const ACCOUNT_UNBLOCK_SUCCESS = 'ACCOUNT_UNBLOCK_SUCCESS'
export const ACCOUNT_UNBLOCK_FAIL = 'ACCOUNT_UNBLOCK_FAIL'

export const ACCOUNT_MUTE_REQUEST = 'ACCOUNT_MUTE_REQUEST'
export const ACCOUNT_MUTE_SUCCESS = 'ACCOUNT_MUTE_SUCCESS'
export const ACCOUNT_MUTE_FAIL = 'ACCOUNT_MUTE_FAIL'

export const ACCOUNT_UNMUTE_REQUEST = 'ACCOUNT_UNMUTE_REQUEST'
export const ACCOUNT_UNMUTE_SUCCESS = 'ACCOUNT_UNMUTE_SUCCESS'
export const ACCOUNT_UNMUTE_FAIL = 'ACCOUNT_UNMUTE_FAIL'

export const ACCOUNT_PIN_REQUEST = 'ACCOUNT_PIN_REQUEST'
export const ACCOUNT_PIN_SUCCESS = 'ACCOUNT_PIN_SUCCESS'
export const ACCOUNT_PIN_FAIL = 'ACCOUNT_PIN_FAIL'

export const ACCOUNT_UNPIN_REQUEST = 'ACCOUNT_UNPIN_REQUEST'
export const ACCOUNT_UNPIN_SUCCESS = 'ACCOUNT_UNPIN_SUCCESS'
export const ACCOUNT_UNPIN_FAIL = 'ACCOUNT_UNPIN_FAIL'

export const FOLLOWERS_FETCH_REQUEST = 'FOLLOWERS_FETCH_REQUEST'
export const FOLLOWERS_FETCH_SUCCESS = 'FOLLOWERS_FETCH_SUCCESS'
export const FOLLOWERS_FETCH_FAIL = 'FOLLOWERS_FETCH_FAIL'

export const FOLLOWERS_EXPAND_REQUEST = 'FOLLOWERS_EXPAND_REQUEST'
export const FOLLOWERS_EXPAND_SUCCESS = 'FOLLOWERS_EXPAND_SUCCESS'
export const FOLLOWERS_EXPAND_FAIL = 'FOLLOWERS_EXPAND_FAIL'

export const FOLLOWING_FETCH_REQUEST = 'FOLLOWING_FETCH_REQUEST'
export const FOLLOWING_FETCH_SUCCESS = 'FOLLOWING_FETCH_SUCCESS'
export const FOLLOWING_FETCH_FAIL = 'FOLLOWING_FETCH_FAIL'

export const FOLLOWING_EXPAND_REQUEST = 'FOLLOWING_EXPAND_REQUEST'
export const FOLLOWING_EXPAND_SUCCESS = 'FOLLOWING_EXPAND_SUCCESS'
export const FOLLOWING_EXPAND_FAIL = 'FOLLOWING_EXPAND_FAIL'

export const RELATIONSHIPS_FETCH_REQUEST = 'RELATIONSHIPS_FETCH_REQUEST'
export const RELATIONSHIPS_FETCH_SUCCESS = 'RELATIONSHIPS_FETCH_SUCCESS'
export const RELATIONSHIPS_FETCH_FAIL = 'RELATIONSHIPS_FETCH_FAIL'

export const FOLLOW_REQUESTS_FETCH_REQUEST = 'FOLLOW_REQUESTS_FETCH_REQUEST'
export const FOLLOW_REQUESTS_FETCH_SUCCESS = 'FOLLOW_REQUESTS_FETCH_SUCCESS'
export const FOLLOW_REQUESTS_FETCH_FAIL = 'FOLLOW_REQUESTS_FETCH_FAIL'

export const FOLLOW_REQUESTS_EXPAND_REQUEST = 'FOLLOW_REQUESTS_EXPAND_REQUEST'
export const FOLLOW_REQUESTS_EXPAND_SUCCESS = 'FOLLOW_REQUESTS_EXPAND_SUCCESS'
export const FOLLOW_REQUESTS_EXPAND_FAIL = 'FOLLOW_REQUESTS_EXPAND_FAIL'

export const FOLLOW_REQUEST_AUTHORIZE_REQUEST =
  'FOLLOW_REQUEST_AUTHORIZE_REQUEST'
export const FOLLOW_REQUEST_AUTHORIZE_SUCCESS =
  'FOLLOW_REQUEST_AUTHORIZE_SUCCESS'
export const FOLLOW_REQUEST_AUTHORIZE_FAIL = 'FOLLOW_REQUEST_AUTHORIZE_FAIL'

export const FOLLOW_REQUEST_REJECT_REQUEST = 'FOLLOW_REQUEST_REJECT_REQUEST'
export const FOLLOW_REQUEST_REJECT_SUCCESS = 'FOLLOW_REQUEST_REJECT_SUCCESS'
export const FOLLOW_REQUEST_REJECT_FAIL = 'FOLLOW_REQUEST_REJECT_FAIL'

export const PINNED_ACCOUNTS_FETCH_REQUEST = 'PINNED_ACCOUNTS_FETCH_REQUEST'
export const PINNED_ACCOUNTS_FETCH_SUCCESS = 'PINNED_ACCOUNTS_FETCH_SUCCESS'
export const PINNED_ACCOUNTS_FETCH_FAIL = 'PINNED_ACCOUNTS_FETCH_FAIL'

export const PINNED_ACCOUNTS_EDITOR_SUGGESTIONS_READY =
  'PINNED_ACCOUNTS_EDITOR_SUGGESTIONS_READY'
export const PINNED_ACCOUNTS_EDITOR_SUGGESTIONS_CLEAR =
  'PINNED_ACCOUNTS_EDITOR_SUGGESTIONS_CLEAR'
export const PINNED_ACCOUNTS_EDITOR_SUGGESTIONS_CHANGE =
  'PINNED_ACCOUNTS_EDITOR_SUGGESTIONS_CHANGE'

export const PINNED_ACCOUNTS_EDITOR_RESET = 'PINNED_ACCOUNTS_EDITOR_RESET'

export const ACCOUNT_REVEAL = 'ACCOUNT_REVEAL'
